<template>
  <div class="prose">
    <h1>Privacy Policy</h1>
    <section>

            <h2>Information We Collect</h2>
            <p>
              We collect the following types of information.
            </p>

            <p>Information you provide us directly.</p>

            <p>
              Your name, e-mail address, and password when you register for an
              account.
            </p>

            <p>
              Communications between you and the site. For example, we may send
              you service related emails (e.g. account verification,
              changes/updates to features of the website, technical and security
              notices).
            </p>

            <h2>How Do We Collect Information</h2>

            <p>
              We collect information directly from you, as well as automatically
              through your user of our Website and, in some cases, from third
              parties.
            </p>

            <p>
              Information That Your Give Us: Typically the information we
              collect directly from you are your contact details, payment or
              billing data, and relationship information like the content of
              customer service requests that you initiate, reviews you submit on
              our service, or responses to surveys. You decide how much
              information you share with us in most cases, but not sharing
              required information may limit your ability to engage in certain
              activities, such as payment information to complete a purchase.
            </p>

            <p>
              Information Collected Automatically: When you use or interact with
              our Website, we receive and store information generated by your
              activity, like Usage Data, and other information automatically
              collected from your browser and mobile device. This information
              may include your IP address; browser type and versionl preferred
              languagel geographic location using IP address or the GPS,
              wireless, or Bluetooth technology on your device; operating system
              and computer platform; purchase history; the full Uniform Resource
              Locator (URL) clickstream to, through and from our Site, including
              date and time; products you viewed or searched for; and areas of
              our Site that you visited. We also may log the length of time of
              your visit and number of times you visit and purchase or use the
              Services. We may assign you one or more unique identifiers to help
              keep track of your future visits.
            </p>

            <p>
              Additionally, we receive and store information generated by users
              visiting your link and submitting Found Forms.
            </p>

            <h2>Use of your personal information</h2>

            <p>We use your personal information to:</p>

            <p>Provide services to you</p>

            <p>Respond to your requests, inquiries, comments or concerns;</p>

            <p>
              Enable you to personalize services and to select content
              you want access to or to share with a third party;
            </p>

            <p>
              Notify you about changes or updates and other
              products and services, including those belonging to related third
              parties;
            </p>

            <p>
              Evaluate and improve the site or service and other products and services and
              to develop new products or services;
            </p>

            <p>
              Identify and analyze usage trends and determine the effectiveness
              of our promotional campaigns;
            </p>

            <p>
              Provide technical, product and other support and help keep
              services working, safe and secure;
            </p>

            <p>Comply with our legal obligations.</p>

            <p>
              We may also combines the personal information that you provide
              with information that we obtain from other sources or that already
              exists in our records for the purposes described above.
            </p>

            <h2>Children Under the Age of 13</h2>

            <p>
              Our Website is not intended for children under 13 years of age. We
              do not knowingly collect personal information from children under
              13. If you are under 13, please do not provide any information on
              this website.
            </p>

            <h2>Mailing Policy</h2>

            <p>
              When you send us an email, we use your email address to thank you
              for your comment and/or reply to your question, and we will store
              your communication and our reply for any future correspondence.
              Beyond our initial reply, we will never use your email address to
              send you any unsolicitated message or information, nor will we
              share it with or sell it to anyone else for such use.
            </p>

            <p>
              When you accept to receive information about our services,
              promotions, newsletters, press releases, and/or new offers we use
              your email address and any other information you give us to
              provide you with the information or other services, until you ask
              us to stop.
            </p>

            <h2>Future changes to the Privacy Policy</h2>

            <p>
              We may update this Privacy Policy as necessary to reflect changes
              we make and to satisfy legal requirements. We will post a
              prominent notice of material changes to our websites. We will
              provide you with other appropriate notice of important changes at
              least 30 days before the effective date.
            </p>

            <h2>Cookies and tracking</h2>

            <p>
              We and our partners may use various technologies to collect and
              store information when you use our Website, and this may include
              using cookies and similar tracking technologies on our Website,
              such as pixels and web beacons to analyze trends, administer the
              website, track users’ movements around the website, serve targeted
              advertisements, and gather demographic information about our user
              base as a whole. Users can control the use of cookies at the
              individual browser level. We partner with third parties to display
              advertising on other sites. Our third party partners may use
              cookies or similar tracking technologies in order to provide you
              advertising or other content based upon your browsing activities
              and interests.{" "}
            </p>

            <h2>Others Working For The Company</h2>

            <p>
              The Company uses certain trusted third parties to help us provide,
              improve, promote and protect the Website. For example, we may use
              third parties to help us provide secure online payment processing.
              These parties may access, process or store your information to
              perform tasks only for the purposes we’ve authorized, and we
              require them to provide at lease the same level of protection for
              you information as described in this Privacy Policy. We may also
              share with third parties aggregated or anonymized information that
              does not directly identify you.
            </p>

            <h2>Data Retention</h2>

            <p>
              The time periods for which we retain your Personal Information
              depend on the purposes for which we use it. We will keep
              your Personal Information for as long as you are a registered
              subscriber or user of our products or for as long as we have
              another business purpose to do so and, thereafter, for no longer
              than is required or permitted by law. The information we collect
              may be stored and processed in servers in the United States and
              wherever we and our service providers have facilities
              around the globe.
            </p>
    </section>
  </div>
</template>

<script>
export default {
  auth: false,
}
</script>
